apiVersion: apps/v1
kind: Deployment
metadata:
  name: telepresence-demo
  labels:
    app: telepresence-demo
spec:
  selector:
    matchLabels:
      app: telepresence-demo
  template:
    metadata:
      labels:
        app: telepresence-demo
    spec:
      containers:
        - name: telepresence-demo
          image: docommunity/hello-node:1.0
          ports:
            - name: http
              containerPort: 9001
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: telepresence-demo
  labels:
    app: telepresence-demo
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 9001
      targetPort: 9001
  selector:
    app: telepresence-demo
